Repository revoreva/kasirsederhana-java, pull requests merged in 2023-10, with the labels that each got.

#5 (FEAT)[KASIR-8][KASIR-9] Save receipt in local session and can be open via admin account
  build/classes/AddOrder$7.class
  build/classes/AddOrder.class
  build/classes/AddOrder.form
  build/classes/AdminMenu$1.class
  build/classes/AdminMenu$2.class
  build/classes/AdminMenu$3.class
  build/classes/AdminMenu$4.class
  build/classes/AdminMenu.class
  build/classes/AdminMenu.form
  build/classes/AllOrder.class
  build/classes/LoginMenu.class
  build/classes/MenuOrdered.class
  build/classes/OrderCenter.class
  build/classes/OrderDate.class
  build/classes/OrderModel.class
  build/classes/ReceiptOrder$1.class
  build/classes/ReceiptOrder$2.class
  build/classes/ReceiptOrder$3.class
  build/classes/ReceiptOrder.class
  build/classes/ReceiptOrder.form
  build/classes/choose_menues.class
  build/classes/detail_order.class
  build/classes/payment$1.class
  build/classes/payment$2.class
  build/classes/payment$3.class
  build/classes/payment$4.class
  build/classes/payment$5.class
  build/classes/payment$6.class
  build/classes/payment.class
  build/classes/query_order.class
  nbproject/private/private.xml
  src/AddOrder.form
  src/AddOrder.java
  src/AdminMenu.form
  src/AdminMenu.java
  src/LoginMenu.java
  src/OrderCenter.java
  src/ReceiptOrder.form
  src/ReceiptOrder.java
  src/choose_menues.java
  src/payment.java
  src/query_order.java
Labels: enhancement, feature

#7 (Enhancement) Edit users: username and password
  build/classes/UsersManagement.class
  src/UsersManagement.java
Labels: enhancement

#8 (CHORE) Update README.md
  README.md
Labels: documentation

#11 (REFACTOR) [KASIR-16] To Support Java Enhancement Aspects, and Rename Some Class from Pascal Case to Camel Case
  nbproject/project.properties
  src/AddOrder.java
  src/AdminMenu.java
  src/ChooseMenus.form
  src/ChooseMenus.java
  src/DetailOrder.form
  src/DetailOrder.java
  src/HardcodedListOfdata.java
  src/LoginMenu.java
  src/MenuCenter.java
  src/OrderCenter.java
  src/QueryMenu.java
  src/QueryOrder.java
  src/ReceiptChecker.java
  src/ReceiptOrder.java
  src/UsersManagement.java
  src/menu_center.java
  src/payment.java
Labels: refactor
